"""build_main_tex.py — assemble final main.tex with inline body.

Reads draft_body.tex and wraps it in a complete LaTeX article preamble
suitable for arXiv submission. Strips the level-1 title section
(handled by \\title) and the abstract section (handled by abstract env).
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

PREAMBLE = r"""% main.tex — arXiv-ready, generated by build_main_tex.py
\documentclass[11pt,letterpaper]{article}

\usepackage[margin=1in]{geometry}
\usepackage[utf8]{inputenc}
\usepackage{amsmath,amssymb,amsthm}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{microtype}
\usepackage[hidelinks]{hyperref}
\usepackage{xcolor}
\usepackage{natbib}
\usepackage{authblk}

\newtheorem{theorem}{Theorem}
\newtheorem{lemma}{Lemma}
\newtheorem{conjecture}{Conjecture}

\graphicspath{{figures/}}

\title{Chain-tier Compounding Amplification in Fractal Monte Carlo Planning:\\
  A Zero-Training Path to Human-Expert Crafter Score}

\author[1]{Anonymous Author}
\affil[1]{Anonymous Affiliation \\\texttt{anonymous@example.org}}

\date{\today}

\begin{document}
\maketitle

\begin{abstract}
"""

POST_ABSTRACT = r"""
\end{abstract}

"""

POSTAMBLE = r"""

\bibliographystyle{plainnat}
\bibliography{references}

\end{document}
"""


def main():
    body_path = HERE / "draft_body.tex"
    if not body_path.exists():
        print("Run md2tex.py first to produce draft_body.tex", file=sys.stderr)
        sys.exit(1)

    body = body_path.read_text()

    # Strip the title section (first \section{Chain-tier...}) — handled by \title
    # Skip from "\section{Chain-tier" up to the next \section or \hrulefill
    body = re.sub(
        r"\\section\{Chain-tier[^}]*\}.*?\\hrulefill",
        "",
        body,
        count=1,
        flags=re.S,
    )

    # Extract abstract block
    m_abs = re.search(
        r"\\section\{Abstract\}\s*(.*?)\\hrulefill",
        body, flags=re.S,
    )
    abstract_body = m_abs.group(1).strip() if m_abs else ""
    body = re.sub(
        r"\\section\{Abstract\}.*?\\hrulefill",
        "",
        body,
        count=1,
        flags=re.S,
    )

    # Demote section levels: the converter used \section for #, \subsection for ##.
    # We want our top-level body to use \section, which it already does.
    # Section names like "1. Introduction" → drop the leading numbering since
    # LaTeX numbers sections automatically.
    body = re.sub(r"\\section\{(\d+\.)\s*", r"\\section{", body)
    body = re.sub(r"\\subsection\{(\d+\.\d+)\s*", r"\\subsection{", body)
    body = re.sub(r"\\subsubsection\{(\d+\.\d+\.\d+)\s*", r"\\subsubsection{", body)

    # Replace \hrulefill (used as section dividers in markdown) with blank lines
    body = body.replace("\\hrulefill", "")

    # Wire image references — figures/fig*.pdf
    # The original draft.md may reference 'paper/figures/' or just 'figures/'.
    # Our \graphicspath{{figures/}} handles 'figures/' → search for 'fig...png'
    # in body, replace with \includegraphics{fig...pdf}
    # (we have both PDFs and PNGs in figures/; prefer PDF)

    out = PREAMBLE + abstract_body + POST_ABSTRACT + body + POSTAMBLE

    out_path = HERE / "main.tex"
    out_path.write_text(out)
    print(f"Wrote {out_path}  ({len(out)} chars, "
          f"{out.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
